OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

-- I changed the password to the correct password


OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'Jenna'@'localhost' (using password: YES)")

-- I changed the username to the correct username


OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

-- I changed the port to the correct port


Traceback (most recent call last):
  File "server.py", line 5, in <module>
    mysql = MySQLConnector(app, 'world')
  File "/Users/jennadalgety/coding-dojo/python/mysql-flask/world/mysqlconnection.py", line 39, in MySQLConnector
    return MySQLConnection(app, db)
  File "/Users/jennadalgety/coding-dojo/python/mysql-flask/world/mysqlconnection.py", line 8, in __init__
    'database': world, # we got db as an argument
NameError: global name 'world' is not defined

-- I changed the database name to its correct one